import type { Metadata } from 'next'
import './globals.css'
import { ReactNode } from 'react'
import { SidebarProvider } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/sidabar/app-sidebar'
import NavBar from '@/components/nav/navBar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <SidebarProvider>
          <AppSidebar />
          <main className='w-full h-svh'>
            <NavBar />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  )
}
